/*
 * Copyright 2020 Nicolo John Davis
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import { Component } from "./types";

// The Schema object contains the specifications of various
// components in a particular game.  It does not change in
// value through the course of the game.  It is
// generated by the Editor and interpreted by the Renderer
// in order to generate the graphics on the frontend.

export interface Schema {
  [id: string]: SchemaEntry;
}

export namespace Style {
  export interface Dimensions {}

  export interface Part {
    type: "box" | "circle";
    x: number;
    y: number;
    width: number;
    height: number;
    fill: string;
    stroke: string;
  }
}

export interface SchemaEntry {
  type: Component;
  data?: KeyValue<any>;
  opts?: KeyValue<any>;
  style?: {
    dimensions: Style.Dimensions;
    parts?: Style.Part[];
  };
}

export interface KeyValue<T> {
  [key: string]: T;
}
